version: "2"

volumes:
  orderer.pharma-supply-network.com:
  peer0.consumer.pharma-supply-network.com:
  peer1.consumer.pharma-supply-network.com:
  peer0.distributor.pharma-supply-network.com:
  peer1.distributor.pharma-supply-network.com:
  peer0.manufacturer.pharma-supply-network.com:
  peer1.manufacturer.pharma-supply-network.com:
  peer0.retailer.pharma-supply-network.com:
  peer1.retailer.pharma-supply-network.com:
  peer0.transporter.pharma-supply-network.com:
  peer1.transporter.pharma-supply-network.com:

networks:
  pharma-network:

services:
  ca.consumer.pharma-supply-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.consumer.pharma-supply-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.registrar.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.registrar.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    volumes:
      - ./crypto-config/peerOrganizations/consumer.pharma-supply-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.consumer.pharma-supply-network.com
    networks:
      - pharma-network

  ca.distributor.pharma-supply-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.distributor.pharma-supply-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/distributor.pharma-supply-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.distributor.pharma-supply-network.com
    networks:
      - pharma-network

  ca.manufacturer.pharma-supply-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manufacturer.pharma-supply-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/manufacturer.pharma-supply-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.manufacturer.pharma-supply-network.com
    networks:
      - pharma-network

  ca.retailer.pharma-supply-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.retailer.pharma-supply-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/retailer.pharma-supply-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.retailer.pharma-supply-network.com
    networks:
      - pharma-network

  ca.transporter.pharma-supply-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.transporter.pharma-supply-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/transporter.pharma-supply-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.transporter.pharma-supply-network.com
    networks:
      - pharma-network

  orderer.pharma-supply-network.com:
    extends:
      file: docker-base/docker-compose-base.yaml
      service: orderer.pharma-supply-network.com
    container_name: orderer.pharma-supply-network.com
    networks:
      - pharma-network

  peer0.consumer.pharma-supply-network.com:
    container_name: peer0.consumer.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.consumer.pharma-supply-network.com
    networks:
      - pharma-network

  peer1.consumer.pharma-supply-network.com:
    container_name: peer1.consumer.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.consumer.pharma-supply-network.com
    networks:
      - pharma-network

  peer0.distributor.pharma-supply-network.com:
    container_name: peer0.distributor.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.distributor.pharma-supply-network.com
    networks:
      - pharma-network

  peer1.distributor.pharma-supply-network.com:
    container_name: peer1.distributor.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.distributor.pharma-supply-network.com
    networks:
      - pharma-network

  peer0.manufacturer.pharma-supply-network.com:
    container_name: peer0.manufacturer.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.manufacturer.pharma-supply-network.com
    networks:
      - pharma-network

  peer1.manufacturer.pharma-supply-network.com:
    container_name: peer1.manufacturer.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.manufacturer.pharma-supply-network.com
    networks:
      - pharma-network

  peer0.retailer.pharma-supply-network.com:
    container_name: peer0.retailer.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.retailer.pharma-supply-network.com
    networks:
      - pharma-network

  peer1.retailer.pharma-supply-network.com:
    container_name: peer1.retailer.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.retailer.pharma-supply-network.com
    networks:
      - pharma-network

  peer0.transporter.pharma-supply-network.com:
    container_name: peer0.transporter.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.transporter.pharma-supply-network.com
    networks:
      - pharma-network

  peer1.transporter.pharma-supply-network.com:
    container_name: peer1.transporter.pharma-supply-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.transporter.pharma-supply-network.com
    networks:
      - pharma-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.9
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.manufacturer.pharma-supply-network.com:7051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/peers/peer0.manufacturer.pharma-supply-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/peers/peer0.manufacturer.pharma-supply-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/peers/peer0.manufacturer.pharma-supply-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/users/Admin@manufacturer.pharma-supply-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.consumer.pharma-supply-network.com
      - ca.distributor.pharma-supply-network.com
      - ca.manufacturer.pharma-supply-network.com
      - ca.retailer.pharma-supply-network.com
      - ca.transporter.pharma-supply-network.com
      - orderer.pharma-supply-network.com
      - peer0.consumer.pharma-supply-network.com
      - peer1.consumer.pharma-supply-network.com
      - peer0.distributor.pharma-supply-network.com
      - peer1.distributor.pharma-supply-network.com
      - peer0.manufacturer.pharma-supply-network.com
      - peer1.manufacturer.pharma-supply-network.com
      - peer0.retailer.pharma-supply-network.com
      - peer1.retailer.pharma-supply-network.com
      - peer0.transporter.pharma-supply-network.com
      - peer1.transporter.pharma-supply-network.com

    networks:
      - pharma-network

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:1.4.9
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.manufacturer.pharma-supply-network.com:7051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/users/Admin@manufacturer.pharma-supply-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/users/Admin@manufacturer.pharma-supply-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/users/Admin@manufacturer.pharma-supply-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-supply-network.com/users/Admin@manufacturer.pharma-supply-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - pharma-network
